-- MySQL Script generated by MySQL Workbench
-- Sex 05 Fev 2016 15:26:52 MST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Visit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Visit` (
  `pk_VisitId` INT UNSIGNED NOT NULL,
  `visit` INT UNSIGNED NOT NULL,
  `mjd` INT NOT NULL,
  `nExposures` INT NOT NULL,
  `exposureType` TEXT NOT NULL,
  `exposureStart` DATETIME NOT NULL,
  `exposureTime` INT NOT NULL,
  `filter` CHAR(1) NOT NULL,
  `telRa` DOUBLE NOT NULL,
  `telDecl` DOUBLE NOT NULL,
  `zenithDistance` FLOAT NOT NULL,
  `airMass` FLOAT NOT NULL,
  `hourAngle` FLOAT NOT NULL,
  PRIMARY KEY (`pk_VisitId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ccd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ccd` (
  `pk_CcdId` INT NOT NULL,
  `fk_VisitId` INT NOT NULL,
  `ccd` TEXT NOT NULL COMMENT 'Some cameras have a name in addition to a ccd number',
  `llra` DOUBLE NOT NULL,
  `lldec` DOUBLE NOT NULL,
  `urra` DOUBLE NOT NULL,
  `urdec` DOUBLE NOT NULL,
  `medianSkyBg` FLOAT NOT NULL,
  `madSkyBg` FLOAT NOT NULL,
  `medianFwhm` FLOAT NOT NULL,
  `madFwhm` FLOAT NOT NULL,
  `medianR50` FLOAT NOT NULL COMMENT 'RMS of the half light radius measured for each source\n',
  `madR50` FLOAT NOT NULL COMMENT 'RMS of the half light radius measured for each source\n',
  `medianMajorAxis` FLOAT NOT NULL,
  `madMajorAxis` FLOAT NOT NULL,
  `medianMinorAxis` FLOAT NOT NULL,
  `madMinorAxis` FLOAT NOT NULL,
  `medianTheta` FLOAT NOT NULL,
  `madTheta` FLOAT NOT NULL,
  `medianScatterRa` FLOAT NOT NULL,
  `madScatterRa` FLOAT NOT NULL,
  `medianScatterDec` FLOAT NOT NULL,
  `madScatterDec` FLOAT NOT NULL,
  `medianScatterPsFlux` FLOAT NOT NULL,
  `madScatterPsFlux` FLOAT NOT NULL,
  `nSources` INT NOT NULL,
  `nCosmicRays` INT NOT NULL,
  `log` TEXT NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`pk_CcdId`),
  INDEX `fk_visit_id_idx` (`fk_VisitId` ASC),
  CONSTRAINT `fk_visit`
    FOREIGN KEY (`fk_VisitId`)
    REFERENCES `mydb`.`Visit` (`pk_VisitId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `mydb`.`QASources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`QASources` (
  `pk_QASourcesId` INT NOT NULL,
  `fk_CcdId` INT NOT NULL,
  `ra` DOUBLE NOT NULL,
  `decl` DOUBLE NOT NULL,
  `fwhm` FLOAT NOT NULL,
  `r50` FLOAT NOT NULL,
  `majorAxis` FLOAT NOT NULL,
  `minorAxis` FLOAT NOT NULL,
  `theta` FLOAT NOT NULL,
  `skyBg` FLOAT NOT NULL,
  `psFlux` FLOAT NOT NULL,
  `psFluxSigma` FLOAT NOT NULL,
  PRIMARY KEY (`pk_QASourcesId`),
  INDEX `ccd_id_idx` (`fk_CcdId` ASC),
  CONSTRAINT `fk_CcdId`
    FOREIGN KEY (`fk_CcdId`)
    REFERENCES `mydb`.`Ccd` (`pk_CcdId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Selected high S/N point sources for image quality measurements';


-- -----------------------------------------------------
-- Table `mydb`.`Metric`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Metric` (
  `pk_MetricId` INT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `units` VARCHAR(16) NOT NULL,
  `condition` VARCHAR(2) NOT NULL,
  `threshold` FLOAT NOT NULL,
  `shortDescription` VARCHAR(128) NOT NULL,
  `description` TEXT NOT NULL,
  `fiducialValue` FLOAT NOT NULL,
  `fiducialValueSigma` FLOAT NOT NULL,
  PRIMARY KEY (`pk_MetricId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CcdToMetric`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CcdToMetric` (
  `pk_ccdToMetricId` INT UNSIGNED NOT NULL,
  `fk_ccdId` INT UNSIGNED NOT NULL,
  `fk_MetricId` INT UNSIGNED NOT NULL,
  `value` FLOAT NOT NULL,
  `rms` FLOAT NOT NULL,
  PRIMARY KEY (`pk_ccdToMetricId`),
  INDEX `fk_ccd_metric_1_idx` (`fk_ccdId` ASC),
  INDEX `fk_CcdToMetric_1_idx` (`fk_MetricId` ASC),
  CONSTRAINT `fk_CcdMetric`
    FOREIGN KEY (`fk_ccdId`)
    REFERENCES `mydb`.`Ccd` (`pk_CcdId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CcdToMetric_1`
    FOREIGN KEY (`fk_MetricId`)
    REFERENCES `mydb`.`Metric` (`pk_MetricId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ReferenceDataset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ReferenceDataset` (
  `pk_ReferenceDatasetId` INT UNSIGNED ZEROFILL NOT NULL,
  `name` TEXT NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`pk_ReferenceDatasetId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dataset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dataset` (
  `pk_DatasetId` INT UNSIGNED ZEROFILL NOT NULL,
  `name` TEXT NOT NULL,
  `description` TEXT NOT NULL,
  `camera` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`pk_DatasetId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `pk_UserId` INT UNSIGNED NOT NULL,
  `name` VARCHAR(16) NOT NULL,
  `displayName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `createTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`pk_UserId`),
  UNIQUE INDEX `user_id_UNIQUE` (`pk_UserId` ASC),
  UNIQUE INDEX `createTime_UNIQUE` (`createTime` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Process`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Process` (
  `pk_ProcessId` INT UNSIGNED NOT NULL,
  `fk_UserId` INT UNSIGNED NOT NULL,
  `fk_DatasetId` INT UNSIGNED NOT NULL,
  `fk_ReferenceDatasetId` INT UNSIGNED NOT NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `description` TEXT NOT NULL,
  `config` TEXT NOT NULL,
  `outputDir` TEXT NOT NULL,
  `status` INT NOT NULL COMMENT '0 - success\n1 - failure\n2 - partial\n',
  PRIMARY KEY (`pk_ProcessId`),
  INDEX `fk_Process_1_idx` (`fk_DatasetId` ASC),
  INDEX `fk_Process_2_idx` (`fk_UserId` ASC),
  INDEX `fk_Process_idx` (`fk_ReferenceDatasetId` ASC),
  CONSTRAINT `fk_Process`
    FOREIGN KEY (`fk_ReferenceDatasetId`)
    REFERENCES `mydb`.`ReferenceDataset` (`pk_ReferenceDatasetId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Process_1`
    FOREIGN KEY (`fk_DatasetId`)
    REFERENCES `mydb`.`Dataset` (`pk_DatasetId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Process_2`
    FOREIGN KEY (`fk_UserId`)
    REFERENCES `mydb`.`User` (`pk_UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProcessToVisit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProcessToVisit` (
  `pk_ProcessToVisitId` INT UNSIGNED NOT NULL,
  `fk_ProcessId` INT UNSIGNED NOT NULL,
  `fk_VisitId` INT UNSIGNED NOT NULL,
  `nSuccess` INT NOT NULL,
  `nFailure` INT NOT NULL,
  PRIMARY KEY (`pk_ProcessToVisitId`),
  INDEX `fk_run_visit_2_idx` (`fk_VisitId` ASC),
  INDEX `fk_ProcessToVisit_idx` (`fk_ProcessId` ASC),
  CONSTRAINT `fk_ProcessToVisit`
    FOREIGN KEY (`fk_ProcessId`)
    REFERENCES `mydb`.`Process` (`pk_ProcessId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProcessToVisit_1`
    FOREIGN KEY (`fk_VisitId`)
    REFERENCES `mydb`.`Visit` (`pk_VisitId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
