-- MySQL Script generated by MySQL Workbench
-- Sáb 30 Jan 2016 20:23:16 MST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`visit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`visit` (
  `visit_id` INT UNSIGNED NOT NULL,
  `visit` INT UNSIGNED NOT NULL,
  `mjd` INT NOT NULL,
  `exp_type` TEXT NOT NULL,
  `exp_start` DATETIME NOT NULL,
  `exp_time` INT NOT NULL,
  `filter` CHAR(1) NOT NULL,
  `tel_ra` DOUBLE NOT NULL,
  `tel_dec` DOUBLE NOT NULL,
  `zd` FLOAT NOT NULL,
  `airmass` FLOAT NOT NULL,
  `ha` FLOAT NOT NULL,
  PRIMARY KEY (`visit_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ccd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ccd` (
  `ccd_id` INT NOT NULL,
  `visit_id` INT NOT NULL,
  `ccd` TEXT NOT NULL COMMENT 'Some cameras have a name in addition to a ccd number',
  `llra` DOUBLE NOT NULL,
  `lldec` DOUBLE NOT NULL,
  `urra` DOUBLE NOT NULL,
  `urdec` DOUBLE NOT NULL,
  `median_sky_bg` FLOAT NOT NULL,
  `mad_sky_bg` FLOAT NOT NULL,
  `median_fwhm` FLOAT NOT NULL,
  `mad_fwhm` FLOAT NOT NULL,
  `median_rh` FLOAT NOT NULL COMMENT 'RMS of the half light radius measured for each source\n',
  `mad_rh` FLOAT NOT NULL COMMENT 'RMS of the half light radius measured for each source\n',
  `median_major_axis` FLOAT NOT NULL,
  `mad_major_axis` FLOAT NOT NULL,
  `median_minor_axis` FLOAT NOT NULL,
  `mad_minor_axis` FLOAT NOT NULL,
  `median_theta` FLOAT NOT NULL,
  `mad_theta` FLOAT NOT NULL,
  `median_scatter_ra` FLOAT NULL,
  `mad_scatter_ra` FLOAT NULL,
  `median_scatter_dec` FLOAT NULL,
  `mad_scatter_dec` FLOAT NULL,
  `median_scatter_flux` FLOAT NULL,
  `mad_scatter_flux` FLOAT NULL,
  `n_srcs` INT NOT NULL,
  `n_crs` INT NOT NULL,
  `log` TEXT NOT NULL,
  PRIMARY KEY (`ccd_id`),
  INDEX `fk_visit_id_idx` (`visit_id` ASC),
  CONSTRAINT `fk_visit`
    FOREIGN KEY (`visit_id`)
    REFERENCES `mydb`.`visit` (`visit_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `mydb`.`qa_src`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`qa_src` (
  `qa_src_id` INT NOT NULL,
  `ccd_id` INT NOT NULL,
  `ra` DOUBLE NOT NULL,
  `dec` DOUBLE NOT NULL,
  `fwhm` FLOAT NOT NULL,
  `rh` FLOAT NOT NULL,
  `major_axis` FLOAT NOT NULL,
  `minor_axis` FLOAT NOT NULL,
  `theta` FLOAT NOT NULL,
  `sky_bg` FLOAT NOT NULL,
  `ps_flux` FLOAT NOT NULL,
  `ps_flux_sigma` FLOAT NOT NULL,
  PRIMARY KEY (`qa_src_id`),
  INDEX `ccd_id_idx` (`ccd_id` ASC),
  CONSTRAINT `fk_ccd_id`
    FOREIGN KEY (`ccd_id`)
    REFERENCES `mydb`.`ccd` (`ccd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Selected high S/N point sources for image quality measurements';


-- -----------------------------------------------------
-- Table `mydb`.`ccd_metric`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ccd_metric` (
  `ccd_metric_id` INT UNSIGNED NOT NULL,
  `ccd_id` INT UNSIGNED NOT NULL,
  `value` FLOAT NOT NULL,
  `rms` FLOAT NOT NULL,
  PRIMARY KEY (`ccd_metric_id`),
  INDEX `fk_ccd_metric_1_idx` (`ccd_id` ASC),
  CONSTRAINT `fk_ccd_metric`
    FOREIGN KEY (`ccd_id`)
    REFERENCES `mydb`.`ccd` (`ccd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`metric`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`metric` (
  `metric_id` INT UNSIGNED NOT NULL,
  `ccd_metric_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `units` VARCHAR(16) NOT NULL,
  `description` TEXT NOT NULL,
  `threshold` FLOAT NOT NULL,
  `short_description` VARCHAR(128) NOT NULL,
  `condition` VARCHAR(2) NOT NULL,
  `fiducial_value` FLOAT NOT NULL,
  `fiducial_value_rms` FLOAT NOT NULL,
  PRIMARY KEY (`metric_id`),
  INDEX `fk_metric_idx` (`ccd_metric_id` ASC),
  CONSTRAINT `fk_metric`
    FOREIGN KEY (`ccd_metric_id`)
    REFERENCES `mydb`.`ccd_metric` (`ccd_metric_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_id` INT UNSIGNED NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC));


-- -----------------------------------------------------
-- Table `mydb`.`run`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`run` (
  `run_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `description` TEXT NOT NULL,
  `config` TEXT NOT NULL,
  `output_dir` TEXT NOT NULL,
  `status` INT NOT NULL COMMENT '0 - success\n1 - failure\n2 - partial\n',
  PRIMARY KEY (`run_id`),
  INDEX `fk_run_2_idx` (`user_id` ASC),
  CONSTRAINT `fk_run_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`run_visit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`run_visit` (
  `run_visit` INT UNSIGNED NOT NULL,
  `visit_id` INT UNSIGNED NOT NULL,
  `run_id` INT UNSIGNED NOT NULL,
  `n_processed` INT NOT NULL,
  `n_failed` INT NOT NULL,
  PRIMARY KEY (`run_visit`),
  INDEX `fk_run_visit_1_idx` (`visit_id` ASC),
  INDEX `fk_run_visit_2_idx` (`run_id` ASC),
  CONSTRAINT `fk_run_visit_1`
    FOREIGN KEY (`visit_id`)
    REFERENCES `mydb`.`visit` (`visit_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_run_visit_2`
    FOREIGN KEY (`run_id`)
    REFERENCES `mydb`.`run` (`run_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dataset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dataset` (
  `dataset_id` INT UNSIGNED ZEROFILL NOT NULL,
  `run_id` INT UNSIGNED NOT NULL,
  `name` TEXT NOT NULL,
  `description` TEXT NOT NULL,
  `camera` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`dataset_id`),
  INDEX `fk_dataset_1_idx` (`run_id` ASC),
  CONSTRAINT `fk_dataset_1`
    FOREIGN KEY (`run_id`)
    REFERENCES `mydb`.`run` (`run_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ref_dataset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ref_dataset` (
  `ref_dataset_id` INT UNSIGNED ZEROFILL NOT NULL,
  `run_id` INT UNSIGNED NOT NULL,
  `name` TEXT NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`ref_dataset_id`),
  INDEX `fk_dataset_1_idx` (`run_id` ASC),
  CONSTRAINT `fk_dataset_10`
    FOREIGN KEY (`run_id`)
    REFERENCES `mydb`.`run` (`run_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
